
services:
  sweety-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4210:80"
      - "4230:443"
    container_name: sweety-app
    restart: unless-stopped
    environment:
      - TZ=Africa/Johannesburg
    volumes:
#      - .:/usr/src/app
#      - /app/node_modules
      - /mnt/app/certs/certs:/etc/nginx/certs:ro

  sweety-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    container_name: sweety-app-dev
    restart: unless-stopped
    mem_limit: 2000m
    cpus: 1
    environment:
      - TZ=Africa/Johannesburg
    volumes:
      - .:/usr/src/app
      - /app/node_modules
      - /mnt/app/certs/certs:/certs:ro


  sweety-tomcat:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    container_name: sweety-tomcat
    ports:
      - "4201:8080"
  sweety-wildfly:
    build:
      context: .
      dockerfile: Dockerfile.wildfly
    container_name: sweety-wildfly
    ports:
      - "4202:8080"
      - "3018:9990"
    restart: unless-stopped
  sweety-apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: sweety-apache
    ports:
      - "4203:80"
    restart: unless-stopped
  # Load Balancer
  sweety-haproxy:
    image: haproxy:alpine
    container_name: sweety-haproxy
    restart: unless-stopped
    ports:
      - "4204:80"
    volumes:
      - /mnt/app/certs/certs:/etc/haproxy/certs:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - sweety-wildfly
      - sweety-tomcat
