networks:
  sweety-sweet-network-bridge:
    driver: bridge
    external: true
    
  sweety-sweet-tunnel:
    driver: bridge
    external: true
    
  node-exporter:
    driver: bridge
    external: true
    

volumes:
  certs:
    external: true

services: 
  sweety-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: sweety-app
    restart: unless-stopped
    environment:
      - TZ=Africa/Johannesburg
    networks:
      - sweety-sweet-network-bridge
      - sweety-sweet-tunnel
      - node-exporter
    volumes:
      - .:/usr/src/app
      - /app/node_modules
       - certs:/certs

  sweety-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4210:4200"
    container_name: sweety-app-dev
    restart: unless-stopped
    mem_limit: 2000m
    cpus: 1
    environment:
      - TZ=Africa/Johannesburg
    networks:
      - sweety-sweet-network-bridge
      - sweety-sweet-tunnel
      - node-exporter
    volumes:
      - .:/usr/src/app
      - /app/node_modules
       - certs:/certs


  sweety-tomcat:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    container_name: sweety-tomcat
    ports:
      - "4201:8080"
    networks:
      - sweety-sweet-network-bridge
      - sweety-sweet-tunnel
      - node-exporter

  sweety-wildfly:
    build:
      context: .
      dockerfile: Dockerfile.wildfly
    container_name: sweety-wildfly
    ports:
      - "4202:8080"
      - "3000:9990"
    restart: unless-stopped
    networks:
      - sweety-sweet-network-bridge
      - sweety-sweet-tunnel
      - node-exporter

  sweety-apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: sweety-apache
    ports:
      - "4203:80"
    restart: unless-stopped
    networks:
      - sweety-sweet-network-bridge
      - sweety-sweet-tunnel
      - node-exporter

  # Load Balancer
  sweety-haproxy:
    image: haproxy:alpine
    container_name: sweety-haproxy
    restart: unless-stopped
    ports:
      - "4204:80"
    volumes:
      - certs:/etc/haproxy/certs:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - sweety-wildfly
      - sweety-tomcat
    networks:
      - sweety-sweet-tunnel
      - node-exporter